#!/usr/bin/env node
'use strict';

// Reads scripts/content.json (plaintext, gitignored), encrypts it with a PIN you
// provide, and writes ../data.js containing only crypto constants — no plaintext
// content ever lands in data.js or in git history.
//
// Usage: node scripts/build-content.js
// Optional non-interactive usage: node scripts/build-content.js --pin 1234

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');

const ITERATIONS = 300000;
const CONTENT_PATH = path.join(__dirname, 'content.json');
const OUTPUT_PATH = path.join(__dirname, '..', 'data.js');

function readPinFromArgs() {
  const idx = process.argv.indexOf('--pin');
  if (idx === -1) return null;
  return process.argv[idx + 1] || null;
}

function promptPin() {
  return new Promise((resolve) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    rl.question('Enter your 4 or 6 digit PIN (typed in plain sight — use a private terminal): ', (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

function validatePin(pin) {
  if (!/^\d{4}$/.test(pin) && !/^\d{6}$/.test(pin)) {
    throw new Error('PIN must be exactly 4 or 6 digits.');
  }
}

async function main() {
  if (!fs.existsSync(CONTENT_PATH)) {
    console.error(`Missing ${CONTENT_PATH}.\nCopy scripts/content.example.json to scripts/content.json and edit it first.`);
    process.exit(1);
  }

  const pin = readPinFromArgs() || (await promptPin());
  validatePin(pin);

  const contentJson = fs.readFileSync(CONTENT_PATH, 'utf8');
  JSON.parse(contentJson); // fail fast on malformed content.json

  const salt = crypto.randomBytes(16);
  const iv = crypto.randomBytes(12);
  const pinBytes = Buffer.from(pin, 'utf8');

  // Fast-fail SHA-256 hash — cheap "wrong PIN" UI feedback before the heavier
  // PBKDF2 derivation below. NOT the real security gate (see README threat model).
  const pinHashHex = crypto.createHash('sha256').update(Buffer.concat([salt, pinBytes])).digest('hex');

  // Real gate: PBKDF2-derived AES-256-GCM key. Wrong PIN -> wrong key -> GCM
  // auth-tag verification fails on decrypt in the browser.
  const key = crypto.pbkdf2Sync(pinBytes, salt, ITERATIONS, 32, 'sha256');

  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const encrypted = Buffer.concat([cipher.update(contentJson, 'utf8'), cipher.final()]);
  const authTag = cipher.getAuthTag();
  // Append the 16-byte GCM auth tag to match the Web Crypto SubtleCrypto
  // AES-GCM convention (tag appended to ciphertext), so app.js can decrypt
  // this directly with crypto.subtle.decrypt without any tag bookkeeping.
  const ciphertext = Buffer.concat([encrypted, authTag]);

  const output = `// AUTO-GENERATED by scripts/build-content.js — do not hand-edit.
// Contains crypto constants only. No plaintext content. Regenerate after
// editing scripts/content.json: node scripts/build-content.js
window.APP_CRYPTO = {
  pinLength: ${pin.length},
  iterations: ${ITERATIONS},
  pinHashHex: ${JSON.stringify(pinHashHex)},
  saltB64: ${JSON.stringify(salt.toString('base64'))},
  ivB64: ${JSON.stringify(iv.toString('base64'))},
  ciphertextB64: ${JSON.stringify(ciphertext.toString('base64'))}
};
`;

  fs.writeFileSync(OUTPUT_PATH, output, 'utf8');
  console.log(`Wrote ${OUTPUT_PATH} (${pin.length}-digit PIN, ${ITERATIONS} PBKDF2 iterations).`);
  console.log('Remember to bump CACHE_VERSION in sw.js before redeploying.');
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
